services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: TZ
        value: America/Sao_Paulo

      # Variáveis corretas para banco PostgreSQL
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRES_HOST
        value: dpg-d20ja7be5dus73dfthhg-a.oregon-postgres.render.com
      - key: DB_POSTGRES_PORT
        value: "5432"
      - key: DB_POSTGRES_DATABASE
        value: n8n_4ib5
      - key: DB_POSTGRES_USER
        value: n8n
      - key: DB_POSTGRES_PASSWORD
        value: uJYxHmNwvQ5hf7FOP3grUtIRnp85ffqK
      - key: DB_POSTGRES_SCHEMA
        value: public
      - key: DB_POSTGRES_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRES_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # TLS: permite ignorar certificados autoassinados
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"

      # Permissões do arquivo de configuração
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
