services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: TZ
        value: America/Sao_Paulo

      # 🎯 Configuração de DB com SSL habilitado corretamente
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: dpg-d20ja7be5dus73dfthhg-a.oregon-postgres.render.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_4ib5
      - key: DB_POSTGRESDB_USER
        value: n8n
      - key: DB_POSTGRESDB_PASSWORD
        value: uJYxHmNwvQ5hf7FOP3grUtIRnp85ffqK
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # 🔐 Segurança e limpeza
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
 
